services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: production
      LOG_LEVEL: info
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      SESSION_DRIVER: cookie
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-betalent}
      DB_DATABASE: ${DB_DATABASE:-betalent}
      GATEWAY1_URL: http://gateways-mock:3001
      GATEWAY2_URL: http://gateways-mock:3002
      GATEWAY1_LOGIN: ${GATEWAY1_LOGIN:-dev@betalent.tech}
      GATEWAY1_TOKEN: ${GATEWAY1_TOKEN:-FEC9BB078BF338F464F96B48089EB498}
      GATEWAY2_AUTH_TOKEN: ${GATEWAY2_AUTH_TOKEN:-tk_f2198cc671b5289fa856}
      GATEWAY2_AUTH_SECRET: ${GATEWAY2_AUTH_SECRET:-3d15e8ed6131446ea7e3456728b1211f}
    depends_on:
      mysql:
        condition: service_healthy
      gateways-mock:
        condition: service_started
    restart: unless-stopped

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-betalent}
      MYSQL_DATABASE: ${DB_DATABASE:-betalent}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  gateways-mock:
    image: matheusprotzen/gateways-mock
    ports:
      - "3001:3001"
      - "3002:3002"
    restart: unless-stopped

volumes:
  mysql_data:
