/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Purchases: () => import('#controllers/purchases_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  Products: () => import('#controllers/products_controller'),
}
