/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'

export class ClientSchema extends BaseModel {
  static $columns = ['email', 'id', 'name'] as const
  $columns = ClientSchema.$columns
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
}

export class GatewaySchema extends BaseModel {
  static $columns = ['id', 'isActive', 'name', 'priority'] as const
  $columns = GatewaySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string | null
  @column()
  declare priority: number | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['amount', 'id', 'name'] as const
  $columns = ProductSchema.$columns
  @column()
  declare amount: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
}

export class TransactionProductSchema extends BaseModel {
  static $columns = ['id', 'price', 'productId', 'quantity', 'transactionId'] as const
  $columns = TransactionProductSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare price: number
  @column()
  declare productId: number
  @column()
  declare quantity: number
  @column()
  declare transactionId: number
}

export class TransactionSchema extends BaseModel {
  static $columns = ['amount', 'cardLastNumbers', 'clientId', 'externalId', 'gatewayId', 'id', 'status'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare amount: number
  @column()
  declare cardLastNumbers: string
  @column()
  declare clientId: number
  @column()
  declare externalId: string
  @column()
  declare gatewayId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
}

export class UserSchema extends BaseModel {
  static $columns = ['email', 'id', 'password', 'role'] as const
  $columns = UserSchema.$columns
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
}
